AWSTemplateFormatVersion: "2010-09-09"
Description: This stack deploys the cognito values

Resources:
  #
  # Cognito and IAM
  #
  # Creates a user pool in cognito to auth against
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: MysfitsUserPool
      AutoVerifiedAttributes:
        - email
          # Creates a User Pool Client to be used by the identity pool
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: MysfitsUserPoolClient
      GenerateSecret: false
      UserPoolId: !Ref UserPool

Outputs:
  CognitoUserPoolId:
    Description: Cognito Userpool Id
    Value: !Ref UserPool
    Export:
      Name: CognitoUserPoolId
  CognitoUserPoolArn:
    Description: Cognito Userpool Arn
    Value: !GetAtt UserPool.Arn
    Export:
      Name: CognitoUserPoolArn
  CognitoUserPoolClientId:
    Description: Cognito UserPoolClientId
    Value: !Ref UserPoolClient
    Export:
      Name: CognitoUserPoolClientId
